#!/bin/bash
echo "🚀 Setting up Digital Farm Management Portal"
echo "============================================="
echo ""
echo "📦 Installing dependencies..."
npm install
echo ""
echo "✅ Setup complete!"
echo ""
echo "🌟 Available commands:"
echo "  npm start     - Start development server"
echo "  npm run build - Build for production"
echo "  npm test      - Run tests"
echo ""
echo "🌐 Application will be available at:"
echo "  http://localhost:3000"
echo ""
echo "🎯 Smart India Hackathon 2024 - Ready to demo!"
echo "🚜 Digital Farm Management Portal"